### ISSUE TITLE
Circumvent the need for Github token to install this package

### ISSUE THREAD

**Issue by just214** [APSPhysics/eslint-config#9]
After digging further (and a helpful tip from @digioi), it appears that the usage of any Github packages (private or public) still require a Github token with read permissions:

[https://github.com/orgs/community/discussions/190371](https://github.com/orgs/community/discussions/19037)

@digioi provided an article that suggests that we may be able to provide read access to our member and/or teams on Github, which may allow us to circumvent the necessity for each developer to generate a Github token and supply it to each project that requires this package. Here is the article:

[https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility] (https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility)

I don't appear to have the permissions or full understanding of this so I am tagging @papile.

The only other options that I know of are to:

1. Just require the Github token as it currently is, however, this creates more friction for our development team.
2. Rename the repo to `eslint-config-apsphysics` and publish it to NPM. This would create a small breaking change in how the package is used, but easily fixable in each project that currently uses the Github package.

**Comment by papile** [comment]
So from that article, it is what we are doing. We have our "All Developers" group having access to that package. That still needs a key (Personal Access Token). I think our pattern of having a local npmrc with the ENV for the token is pretty low friction. We expect this to be in a developer's environment and in the production environment. Many projects are going to need private packages anyway and things like Fontawesome. So we just make this part of our onboarding to develop. It would have been a little nicer if they didn't need that key but it isn't too terrible if we need it.

I think with the publishing packages to NPM, we should see first if we have more things that would fit that pattern or it can alleviate a large burden. Since everything is in GH packages that we run in Java, Ruby and Javascript it is more consistent to be publishing and pulling from there.

**Comment by just214** [comment]
Documentation has been added to the project README on how to configure Github token for usage of this package.
